global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ms-ppt-metricas'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['metricas:9090']
        labels:
          application: 'My Ms-ppt-metricas'
