# ===============================
# SERVER
# ===============================
server:
  port: 8080
  servlet:
    context-path: /ms-ppt-metricas

# ===============================
# springdoc
# ===============================
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    


## Formato de las fechas
spring:
  h2:
    console:
      enabled: true
      path: /h2
    
  datasource:
    url: jdbc:h2:file:./db-h2/spring-boot-h2-db
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    initialization-mode: always
    platform: h2
  jpa:
    hibernate:
      ddl-auto: update

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Santiago

# ===============================
# LOGS SETTINGS
# ===============================
logging:
  config: classpath:logback-spring.xml
  level:
    cl.fseguel: ERROR
    org.springframework: ERROR
# ===============================
# SPRING
# ===============================
#spring:
#  profiles:
#    active: local

# ===============================
# Metrics management.endpoints.web.exposure.include=health,info,prometheus
# ===============================
management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: [ "*" ]
  tracing:
    enabled: true
    propagation:
      type: b3
    sampling:
      probability: 1.0

  zipkin:
    tracing:
#        endpoint: http://192.168.0.218:9411/api/v2/spans
        endpoint: http://zipkin:9411/api/v2/spans
        